site_name: Project Dukkha
theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.critic
plugins:
  - search
  - gen-files:
      scripts: []
  - bibtex:
      bib_file: docs/data/references.bib
  - macros
  - awesome-pages
  - glightbox
nav:
  - Home: index.md
  - Manifesto:
      - manifesto/index.md
  - Truth:
      - truth/index.md
  - Model:
      - model/index.md
  - Research:
      - research/index.md
      - research/R1.md
  - Practice:
      - practice/index.md
  - Briefs:
      - briefs/index.md
  - Library:
      - library/index.md
extra_css:
  - assets/dukkha.css
